language: java
jdk:
  - oraclejdk8
  - openjdk7

sudo: false
dist: trusty

# shorten the VM hostname with the new workaround
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
     hosts:
        - myshorthost
     hostname: myshorthost

install: true
"script": [
    "./gradlew testRealtimeSuite",
    "./gradlew testRestSuite"
]
